version: '3.2'
services:
  sentimentalyzer:
    build: ../
    environment:
      - PORT=8123
  cypress:
    image: "mtlynch/cypress:3.2.0"
    depends_on:
      - sentimentalyzer
    environment:
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    working_dir: /app
    volumes:
      - ./cypress:/app/cypress
      # Traverse in and out of the e2e directory so that docker-compose will
      # mount a single file as a volume.
      - ../e2e/cypress.json:/app/cypress.json
